### ISSUE TITLE
感觉是一个不错的想法，但是我看文档，针对于需要定制化生成 Mapper 逻辑怎么体现

### ISSUE THREAD

**Issue by springandme** [linpeilie/mapstruct-plus#10]

**Comment by linpeilie** [comment]
> 

例如？需要哪一方面的定制化。

目前根据我和一些使用者的意见，提改了转换过程中的一些配置，可能有其他的场景没有想到。欢迎提出意见

**Comment by springandme** [comment]
比如官方的 org.mapstruct.Mapper 注解，提供很多配置项，来指导生成的 mapper 逻辑，常见配置相应的数据类型转换器、NULL 值处理。本框架是自动生成相应的 mapper，这种情况如何与原有的 mapstruct 功能进行集成

**Comment by linpeilie** [comment]
> 比如官方的 org.mapstruct.Mapper 注解，提供很多配置项，来指导生成的 mapper 逻辑，常见配置相应的数据类型转换器、NULL 值处理。本框架是自动生成相应的 mapper，这种情况如何与原有的 mapstruct 功能进行集成

AutoMapper注解提供了uses属性，支持自定义转换器；
AutoMapping注解提供了几个常用的属性转换配置，也有你说的默认值这种。

目前只支持了我认为常用的配置项，并没有支持所有的配置项。如果有需要的，可以提一下，我来加一下

**Comment by linpeilie** [comment]
> 比如官方的 org.mapstruct.Mapper 注解，提供很多配置项，来指导生成的 mapper 逻辑，常见配置相应的数据类型转换器、NULL 值处理。本框架是自动生成相应的 mapper，这种情况如何与原有的 mapstruct 功能进行集成

AutoMapper对应生成的就是转换接口接口上面的Mapper注解，AutoMapping最终生成，对应的就是属性上面的Mapping配置注解。
