### ISSUE TITLE
MapperConfig无法在公共jar包中使用？

### ISSUE THREAD

**Issue by tfnick** [linpeilie/mapstruct-plus#103]
【问题】
package org.xxx;

import io.github.linpeilie.annotations.MapperConfig;

@MapperConfig(
        mapperPackage="org.xxx.gen",
        autoConfigPackage="org.xxx.gen.config",
        adapterPackage="org.xxx.gen.adapter"
)
public class MapStructPlusConfiguration {
      //mapstruct plus generate config
}

我定义了一个公共配置，作为framework.jar的一部分，项目project_demo依赖framework.jar之后，生成的代码并不在预期的pakcage:org.xxx.gen之下。
【期望】
每个子项目不需要单独定义一个MapStructPlusConfiguration类，每个子项目通过依赖framework.jar即可，项目有共同的生成代码目录：org.xxx.gen

**Comment by linpeilie** [comment]
是的，这个不支持跨模块配置，可以通过compilerArgs参数的方式，来统一配置
