### ISSUE TITLE
javax.annotation.processing.FilerException

### ISSUE THREAD

**Issue by liucq200518** [linpeilie/mapstruct-plus#104]
Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Source file already created: /api-place-manage/target/generated-sources/annotations/com/hushan/place/domain/PlaceTypeToPlaceTypeVOMapperImpl.java  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:59)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:39)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:29)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:24)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:141)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:112)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)  	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)  	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:972)  	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:449)  	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:414)  	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:211)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:345)  	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:286)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:192)  	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)  	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)  	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)  	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)  	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)  	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)  	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)  	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)  Caused by: javax.annotation.processing.FilerException: Source file already created: /api-place-manage/target/generated-sources/annotations/com/hushan/place/domain/PlaceTypeToPlaceTypeVOMapperImpl.java  	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.createSourceFile(IdeFilerImpl.java:161)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:56)  	... 33 more  

<annotationProcessorPaths>
                        <path>
                            <groupId>com.github.therapi</groupId>
                            <artifactId>therapi-runtime-javadoc-scribe</artifactId>
                            <version>0.15.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot.version}</version>
                        </path>
                        <path>
                            <groupId>io.github.linpeilie</groupId>
                            <artifactId>mapstruct-plus-processor</artifactId>
                            <version>${mapstruct-plus.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${mapstruct-plus.lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>

**Comment by linpeilie** [comment]
什么环境？

**Comment by cdisk** [comment]
就是有这个问题，我也遇到了。
![image](https://github.com/user-attachments/assets/08a0cdf6-5c2d-4b6c-9c3c-74ba727b26b8)
