### ISSUE TITLE
[Question] 不同属性名称映射问题

### ISSUE THREAD

**Issue by fangzhengjin** [linpeilie/mapstruct-plus#107]
有一个场景，看了下文档好像通过Plus的注解目前没有办法直接处理，不知道作者有没有其他比较好的支持方式

首先，存在一个持久化实体对象的基类 `IdEntity`

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
public abstract class IdEntity implements Serializable {
    private Long id;
}
```

持久化实体为`Test`,需要将`Test`转为`TestDto`
```java
@AutoMappers({
        @AutoMapper(target = Test.class),
        @AutoMapper(target = TestDto.class)
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Test extends IdEntity {
    private Long test;
}
```

`Test`与`TestDto`不在同一个Jar包中，但`Test`所在Jar依赖`TestDto`所在Jar
```java
// 还存在此Dto转其他Dto的情况
@AutoMapper(target = TestInfoDto.class)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TestDto implements Serializable {
    private Long testId;
}
```

这时无法在`TestDto`中的`testId`上添加`@AutoMapping(source = Test.class, target = "id")`, 因为`TestDto`依赖的Jar中不存在`Test`
也无法修改`IdEntity`

有什么其他好的方式可以将`Test`转换成`TestDto`时将`Test.id`赋予`TestDto.testId`吗？

**Comment by linpeilie** [comment]
可以在 `Test` 类的属性上面，添加 `@ReverseAutoMapping` 属性，配置如下：
```java
@AutoMappers({
        @AutoMapper(target = Test.class),
        @AutoMapper(target = TestDto.class)
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Test extends IdEntity {
    @ReverseAutoMapping(source = 'testId', target = 'id')
    private Long test;
}
```

**Comment by linpeilie** [comment]
如果 `AutoMappers` 配置了两个类，`@ReverseAutoMapping` 还可以指定 `targetClass` 为 `TestDto`

**Comment by fangzhengjin** [comment]
> 可以在 `Test` 类的属性上面，添加 `@ReverseAutoMapping` 属性，配置如下：
> 
> ```java
> @AutoMappers({
>         @AutoMapper(target = Test.class),
>         @AutoMapper(target = TestDto.class)
> })
> @Data
> @NoArgsConstructor
> @AllArgsConstructor
> public class Test extends IdEntity {
>     @ReverseAutoMapping(source = 'testId', target = 'id')
>     private Long test;
> }
> ```

可是 `private Long test;`这个属性和 `testId `与`id` 没有任何关系，这么写可以吗？
目标需求是想把 `Test` 转换为 `TestDto` 但是 `Test` 的 `id` 属性是在父类中，`TestDto` 中不叫`id`而是`testId`

**Comment by fangzhengjin** [comment]
在没有办法修改目标类和父类的情况下，将父类的属性复制到目标类的不同名属性中，感觉是不是应该有一个在类上的注解来标记这种做法？

**Comment by linpeilie** [comment]
> > 可以在 `Test` 类的属性上面，添加 `@ReverseAutoMapping` 属性，配置如下：
> > 
> > ```java
> > @AutoMappers({
> >         @AutoMapper(target = Test.class),
> >         @AutoMapper(target = TestDto.class)
> > })
> > @Data
> > @NoArgsConstructor
> > @AllArgsConstructor
> > public class Test extends IdEntity {
> >     @ReverseAutoMapping(source = 'testId', target = 'id')
> >     private Long test;
> > }
> > ```
> 
> 可是 `private Long test;`这个属性和 `testId `与`id` 没有任何关系，这么写可以吗？
> 目标需求是想把 `Test` 转换为 `TestDto` 但是 `Test` 的 `id` 属性是在父类中，`TestDto` 中不叫`id`而是`testId`

可以的，你可以试一下

**Comment by fangzhengjin** [comment]
试了一下，没有看到效果，在生成的 `TestToTestDtoMapperImpl` 中没有看到相关内容

**Comment by linpeilie** [comment]
是要 `Test` 转为 `TestDto` 是吧，最开始给我的描述信息是想要在 `TestDto` 属性上面加注解，搞得我看错了，那可以直接这样子：

```java
@AutoMappers({
        @AutoMapper(target = Test.class),
        @AutoMapper(target = TestDto.class)
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Test extends IdEntity {
    @AutoMapping(source = 'id', target = 'testId')
    public void getId() {
        return super.getId();
    }

    private Long test;
}
```

加一个 getter 方法，是为了你觉得放在test属性上面奇怪，可以用这种方式

**Comment by fangzhengjin** [comment]
> 是要 `Test` 转为 `TestDto` 是吧，最开始给我的描述信息是想要在 `TestDto` 属性上面加注解，搞得我看错了，那可以直接这样子：
> 
> ```java
> @AutoMappers({
>         @AutoMapper(target = Test.class),
>         @AutoMapper(target = TestDto.class)
> })
> @Data
> @NoArgsConstructor
> @AllArgsConstructor
> public class Test extends IdEntity {
>     @AutoMapping(source = 'id', target = 'testId')
>     public void getId() {
>         return super.getId();
>     }
> 
>     private Long test;
> }
> ```
> 
> 加一个 getter 方法，是为了你觉得放在test属性上面奇怪，可以用这种方式

好的好的 太感谢了，如果 `AutoMapping` 和 `ReverseAutoMapping ` 跟实际标记的字段没有强关联的话，这两个注解的复数形式，也就是`AutoMappings` 和 `ReverseAutoMappings` 如果允许标记在类上，是不是更好一点呀？

**Comment by linpeilie** [comment]
后面我考虑一下。
