### ISSUE TITLE
转换方法有两个，想进入T convert(S var1, @MappingTarget T var2)

### ISSUE THREAD

**Issue by thful** [linpeilie/mapstruct-plus#11]
![image](https://user-images.githubusercontent.com/3615301/225821463-a27f8cbf-af69-4c54-b20f-a00bc3128e13.png)
打什么标注，才能让代码走下面这个转换方法？
T convert(S var1, @MappingTarget T var2);

自动生成的转换代码中，只有下面的这个方法，才能在原实体中set而非new一个新的实体。
![image](https://user-images.githubusercontent.com/3615301/225821814-d777c234-1102-4019-a8f9-175c3488d3a9.png)
想让代码进入下面的这个转换方法中。

**Comment by linpeilie** [comment]
问题1.1.7已解决
