### ISSUE TITLE
请问配置一个类与多个类进行转换时，代码端要怎么写？

### ISSUE THREAD

**Issue by seven-mz** [linpeilie/mapstruct-plus#111]
@Data
@AutoMappers({
    @AutoMapper(target = UserDto.class),
    @AutoMapper(target = UserVO.class)
})
public class User {
    // fields
}
        使用
        UserDto userDTO=new  UserDto();
        User user=Converter.convert(userDTO,User.class);
        UserVO userVO=new  UserVO();
        user = MapstructUtils.convert(userVO, User.class);
        这样写是错误的，第一个对象的值会变null  没找到传入多个对象的转成一个对象的convert方法

**Comment by linpeilie** [comment]
不支持这种转换的，如果需要这种，可以定义 MapStruct 原生转换接口的方式来实现
