### ISSUE TITLE
生成转化器异常jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoClassDefFoundError: io/github/linpeilie/Converter

### ISSUE THREAD

**Issue by YuanJie2001** [linpeilie/mapstruct-plus#112]
jdk21
springboot3.0.2
<lombok.version>1.18.34</lombok.version>
<mapstruct-plus.version>1.4.5</mapstruct-plus.version>
如下图，生成转化器方法无法找到，已重新编译。我的所有实体都在biz模块，在common模块我抽离了拷贝工具，并引入Converter对象替换BeanUtils

![d1c07389e4f8816231da138e8a2a5c8c](https://github.com/user-attachments/assets/7b4d62a2-514b-4acd-9a2b-ade51a7a0738)

**Comment by YuanJie2001** [comment]
补图
![fa521eb732f7823c6ca8a5ded7067a69](https://github.com/user-attachments/assets/602ff147-a3ce-4293-a485-f618cf8adc1e)

**Comment by YuanJie2001** [comment]
![000c63bcca4b8e80e300a558cf2a768a](https://github.com/user-attachments/assets/033cd2a9-0714-437c-9c6f-bce71a8ed86a)

**Comment by YuanJie2001** [comment]
![f36077230a386b97dedd1060a8f75999](https://github.com/user-attachments/assets/8daea1e5-fc8b-4173-a5c3-075fe4852e99)
![fd1aec94c4d72922105ee23a7a6fe8c8](https://github.com/user-attachments/assets/8c926b30-778c-4892-a6af-a42323b1005a)

**Comment by linpeilie** [comment]
不要自己这样子new呀，可以参考 `MapstructAutoConfiguration` 中怎么初始化的

**Comment by YuanJie2001** [comment]
哦，但是一般工具类直接静态方法引用，我并没有使用springboot版本。用的mapstruct-plus jar,我看那个demo也是这么new的(*^_^*)
![image](https://github.com/user-attachments/assets/d0f1e4bc-70ab-4f00-b09f-0735ad88f775)

**Comment by linpeilie** [comment]
那个是没有SpringBoot环境的，和你的不一样

**Comment by YuanJie2001** [comment]
对，我怕冲突，也不想使用容器注入。于是引入的剔除springboot版本的。。我只想静态引用

**Comment by YuanJie2001** [comment]
我试过mapstruct-spring-boot-start的 springContextUtils获取，结果一样

**Comment by linpeilie** [comment]
我是说初始化Converter不能这样子，你都没有依赖starter，怎么获取得到

**Comment by YuanJie2001** [comment]
有没有可能昨天所有方案都尝试过了。。。如下图
![57b222adc81b5539385fba301f7d8cfa](https://github.com/user-attachments/assets/7c6a3a69-dede-4def-9594-8ab9df3cb1ac)
![2768d6c3d3d2661748a439de94f2bb71](https://github.com/user-attachments/assets/33d83dc1-2531-4fe7-a030-645b085aeaca)
最终裁决使用非springboot版原因很多。工具类有独立特性，应当更为通用适应很多环境吧。怎么会普通版在springboot里面用不了

**Comment by YuanJie2001** [comment]
补图
![554e1a8157a70aa7e3496fa2eedd54f6](https://github.com/user-attachments/assets/ea632128-e69b-4471-ace4-1baa883724fa)

**Comment by linpeilie** [comment]
你是 converter 类都找不到，不该检查下自己的依赖么，你最终能依赖到 Converter 类所在的包吗？

**Comment by YuanJie2001** [comment]
![e62b66813d2434daa516594400c8583e](https://github.com/user-attachments/assets/a45d8370-c098-47cf-a5f2-81224d4178c2)
这不是么

**Comment by YuanJie2001** [comment]
额，别在意。。，我测试的时候是在业务层debug拦住用的注入

**Comment by linpeilie** [comment]
运行时找不到类，你要看代码启动类所在的包的依赖树，肯定有问题的呀
