### ISSUE TITLE
错误:Couldn't find type io.github.linpeilie.mapstruct.SpringContextUtils4Msp. 

### ISSUE THREAD

**Issue by wangzhijie0602** [linpeilie/mapstruct-plus#117]
我的环境:springboot3 + lombok 1.18.34 + Mapstruct Plus 1.4.6
当我编译的时候发生了上面的错误信息,我确定我引入了正确的maven配置,以及对应的插件
![image](https://github.com/user-attachments/assets/0c753dc0-63d0-42a3-bf6c-b280604288dc)
我在使用Mapstruct Plus 1.4.6进行编译,发生了上述错误
![image](https://github.com/user-attachments/assets/ae5cbf93-5015-406a-9354-b9102c84610d)
当我将Mapstruct Plus 1.4.2的时候,项目成功编译了,并且运行正常

**Comment by linpeilie** [comment]
这个类是1.4.6新加的。建议看一下依赖情况
