### ISSUE TITLE
大佬，如果我有一个接口，定义了几个get方法，转换的时候会报错，找不到对应类型Mapper

### ISSUE THREAD

**Issue by baklpc** [linpeilie/mapstruct-plus#118]
大佬，如果我有一个接口，定义了几个get方法，转换的时候会报错，找不到对应类型Mapper

**Comment by linpeilie** [comment]
没懂具体的问题是什么，提供下示例呢

**Comment by baklpc** [comment]
> 没懂具体的问题是什么，提供下示例呢

明天给你写一个 demo

**Comment by baklpc** [comment]
public interface Base {

    Long getId();

    String getName();

}


@Data
public class Dept implements Base {

    private Long id;

    private String name;

    // 部门其他字段

}


@Data
public class User implements Base {

    private Long id;

    private String name;

    // 用户其他字段

}


@Data
@AutoMappers({ @AutoMapper(target = Base.class, convertGenerate = false) })
public class ResultVO implements java.io.Serializable {

    @Serial
    private static final long serialVersionUID = -1565714816110392790L;

    private Long id;

    private String name;

}

测试用例

        Dept dept = new Dept();
        dept.setId(1L).setName("测试");

        converter.convert(dept, ResultVO.class);

代码其实是正常生成了，只是没有获取到对应类型的Mapper

**报错：io.github.linpeilie.ConvertException: cannot find converter from Dept to ResultVO**

这个使用场景是因为好多框架都是提供接口，实现有好多个，代码里面 converter.convert，不可能会把所有的实现类都写上哈，

还有一个问题是，代码生成的包路径是不是可以设置一下，生成的代码都在某一个包里面，如果按着ResultVO的使用的使用方式，生成的mapper类在对应target的包，但是一般项目都不会扫描非项目外的包路径，还得需要手动指定包路径才能扫到

**Comment by linpeilie** [comment]
不支持直接根据父类来指定转换关系。

如果想要实现这种功能，可以自己实现一下，参考 `SpringConverterFactory` ，重新定义一个 `ConverterFactory`，在寻找转换接口时，当前类如果找不到，则查询父类与目标类的转换接口。
