### ISSUE TITLE
String转List<String>

### ISSUE THREAD

**Issue by Inseparable-Bird** [linpeilie/mapstruct-plus#120]
![image](https://github.com/user-attachments/assets/5e449940-ccd0-47e7-84ba-d4b8f5367d6f)
![image](https://github.com/user-attachments/assets/5e7b17bf-6c93-45ea-a263-a1ccba272953)
![image](https://github.com/user-attachments/assets/dfc2c4cd-6aa9-4a07-b53b-61b2426f7280)
按照案例写的，但是编译的时候报错了：
![image](https://github.com/user-attachments/assets/89d39d5d-9298-4d27-b48d-9834f99edf38)

**Comment by linpeilie** [comment]
你这里报错的是 `DocumentManageModel` 转为 `DocumentManageModelDTO` 时报错了，与你配置的这个没有关系
