### ISSUE TITLE
怎么让自定义类型转换器默认全局生效

### ISSUE THREAD

**Issue by catch6** [linpeilie/mapstruct-plus#121]
<img width="908" alt="image" src="https://github.com/user-attachments/assets/30abae81-50ed-487d-8fc3-8d45c8022c62">
即不使用use，当匹配到类型不同时自动匹配StringToListStringConverter

**Comment by linpeilie** [comment]
转换接口添加mapstruct的mapper注解

**Comment by catch6** [comment]
加了，还是没找到对应的转换器

<img width="499" alt="image" src="https://github.com/user-attachments/assets/8c8b819e-dc33-4535-ae1f-c4af326fb53d">
<img width="469" alt="image" src="https://github.com/user-attachments/assets/1ad2db0e-45f8-4cc5-acdf-1ff62e6e9017">

java: Can't map property "String roles" to "List<String> roles". Consider to declare/implement a mapping method: "List<String> map(String value)". Occured at 'T convert(S arg0)' in 'BaseMapper'

**Comment by linpeilie** [comment]
![image](https://github.com/user-attachments/assets/48d82d67-4c32-4ed6-b3c9-2f5cedb2613e)
参考这部分

**Comment by catch6** [comment]
试了不行的，错误信息：`java: Can't map property "List<String> roles" to "String roles". Consider to declare/implement a mapping method: "String map(List<String> value)". Occured at 'T convert(S arg0)' in 'BaseMapper'.`

完整测试代码：
```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface AppMapper {

	default List<String> stringToListString(String str) {
		if (str == null) {
			return null;
		}
		return List.of(str.split(","));
	}

	default String listStringToString(List<String> strings) {
		if (strings == null) {
			return null;
		}
		return String.join(",", strings);
	}

}
```
```java
@Slf4j
@SpringBootTest
class CatchApplicationTests {

	@Resource
	private Converter converter;

	@Test
	void contextLoads() {
		VO1 vo1 = new VO1();
		vo1.setRoles("1,2,3");
		VO2 vo2 = converter.convert(vo1, VO2.class);
		log.info("vo2: {}", vo2);
		VO1 vo11 = converter.convert(vo2, VO1.class);
		log.info("vo11: {}", vo11);
	}

	@AutoMapper(target = VO2.class)
	@Data
	public static class VO1 {

		private String roles;

	}

	@Data
	public static class VO2 {

		private List<String> roles;

	}

}
```

**Comment by linpeilie** [comment]
在 VO2 上面也加 `AutoMapper(target=VO1.class)`

**Comment by catch6** [comment]
加了，不行的

<img width="408" alt="image" src="https://github.com/user-attachments/assets/9dbad2f4-4f38-4e3a-9a70-1107f1242ebe">
自动生成的代码 target/generated-sources/annotations/com/github/mapstruct/AppMapperImpl.java
<img width="818" alt="image" src="https://github.com/user-attachments/assets/492ade58-a836-4f04-8360-68bc664353e9">

**Comment by linpeilie** [comment]
生成的 VO1 转 VO2 的转换接口呢

**Comment by catch6** [comment]
VO1转VO2没转换接口，这个不是mapstruct自己就有吗，比如两个都有String name就自动转换过去了，只是当String roles和List<String>这种类型不同的时候转换用的

**Comment by catch6** [comment]
看来这种场景还是得用uses，就这样吧

**Comment by linpeilie** [comment]
我问生成的 Vo1 转 Vo2 的接口。我提交了个用例，看 [issue-121 ](https://github.com/linpeilie/mapstruct-plus/tree/issue-121) 这个分支的 `StringToListStringConverter`

**Comment by catch6** [comment]
@linpeilie 我创建了一个最小化示例仓库，你可以clone下来运行下
https://github.com/catch6/mapstruct-plus-demo.git

**Comment by linpeilie** [comment]
服你了，VO1和VO2和AppMapper跨模块了呀，为啥一个要放测试目录

**Comment by catch6** [comment]
ok，原来如此
