### ISSUE TITLE
在使用AutoMappers自动生成代码时，如何屏蔽某个方法不进行生成代码version: 1.5.5.Final

### ISSUE THREAD

**Issue by weijiang157152688** [linpeilie/mapstruct-plus#122]

**Comment by linpeilie** [comment]
没懂什么意思

**Comment by weijiang157152688** [comment]
定义一个
public class A{
private List<Double> loads;

 public List<Order> getPkgOrders() {
        return orderPackage.getOrders();
    }
} 
@AutoMappers({
        @AutoMapper(target = A.class),
})
public class B {
}

如何让自动生成的BToAMapper的代码不进行getPkgOrders方法的任何操作

**Comment by linpeilie** [comment]
你这个例子，会执行 `getPkgOrders` 方法？

**Comment by weijiang157152688** [comment]
是的，实现的convert会执行     
if ( arg1.getPkgOrders() != null ) {
            arg1.getPkgOrders().clear();
            List<Order> list7 = arg0.getPkgOrders();
            if ( list7 != null ) {
                arg1.getPkgOrders().addAll( list7 );
            }
        }

**Comment by linpeilie** [comment]
给我完整的示例。你这个例子怎么可能会执行这段代码

**Comment by weijiang157152688** [comment]
[convert.tar.gz](https://github.com/user-attachments/files/18058457/convert.tar.gz)
![image](https://github.com/user-attachments/assets/35746222-3a11-40ac-8599-0966d01ef4e9)
![image](https://github.com/user-attachments/assets/d51daf92-7d00-4f19-8a4e-67690abc2cd6)

**Comment by weijiang157152688** [comment]
代码：
[convert.tar.gz](https://github.com/user-attachments/files/18058464/convert.tar.gz)

**Comment by linpeilie** [comment]
可以通过 `ignore` 属性来忽略

**Comment by weijiang157152688** [comment]
![image](https://github.com/user-attachments/assets/ba0276fd-8b1a-4801-ae75-3e67d00ddd5b)
这liang z两种都不生效

**Comment by linpeilie** [comment]
![image](https://github.com/user-attachments/assets/f2dd628d-2cf9-440a-8234-bdbc2f8b6beb)
![image](https://github.com/user-attachments/assets/cacd9441-5ad3-4756-b78b-ff425cc5564a)
![image](https://github.com/user-attachments/assets/1c198cd8-e967-43a5-9e90-da1b2931edac)
我试了下是生效的

**Comment by weijiang157152688** [comment]
好的，我知道了
