### ISSUE TITLE
使用mapstruct-plus 进行maven package时报错

### ISSUE THREAD

**Issue by echoa-cheng** [linpeilie/mapstruct-plus#123]
报错信息：Ambiguous constructors found for creating java.lang.Long: Long(long), Long(java.lang.String). Either declare parameterless constructor or annotate the default constructor with an annotation named @Default. Occured at 'Long selectCount(Wrapper queryWrapper)' in 'BaseMapper'.

环境：
IDEA2024.3
JDK:Graalvm 21.0.5
Maven:3.9.9
mapstruct-plus:1.4.6
lombok:1.18.36

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/7256084a-f61a-4ed4-91d7-aa40970eb85f">

已经按照官网进行配置：
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/ebc7a49a-1f2e-4600-a2c4-fab934e8d07d">

**Comment by linpeilie** [comment]
BaseMapper继承错了吧

**Comment by echoa-cheng** [comment]
<img width="1718" alt="image" src="https://github.com/user-attachments/assets/83e06fbe-6111-4878-a958-ed087166afc2" />
这个@mapper的注解引错包了没注意看
