### ISSUE TITLE
多模块项目问题

### ISSUE THREAD

**Issue by khiker007** [linpeilie/mapstruct-plus#21]
我的项目是一个多模块项目，不同模块有不同的domain，vo，单独模块使用可以顺利转换

但是，一个模块如果依赖多个不同模块，代码生成的ConvertMapperAdapter是每个模块一个，在项目启动后会存在冲突和覆盖问题，导致有的converter会找不到方法。

是否可以每个模块指定ConvertMapperAdapter的生成路径，从而避免覆盖问题？
![image](https://user-images.githubusercontent.com/10723358/233794935-ad4593eb-decc-42bd-9797-368e67443a1a.png)

**Comment by linpeilie** [comment]
好的，我增加个配置，来指定ConvertMapperAdapter的类名和包名

**Comment by khiker007** [comment]
辛苦了，期待尽快发布新版本

**Comment by linpeilie** [comment]
可以更新1.2.3了，配置文档可以参考[官网](https://mapstruct.plus/guide/configuration.html)
