### ISSUE TITLE
@MapperConfig配置不起作用的问题

### ISSUE THREAD

**Issue by 853103174** [linpeilie/mapstruct-plus#29]
环境: springboot2.7.7+mapstruct-plus1.2.5+lombok1.18.28+maven3.6.3搭建的多模块项目

根据官网说明配置以后还是生成的默认名称,model和config在不同的子模块中,还有什么要注意的吗

@Component
@ComponentModelConfig
@MapperConfig(mapperPackage = "com.jiajiayue.txjm.shop.sync.converter", adapterClassName = "SyncConvertMapperAdapter", adapterPackage = "com.jiajiayue.txjm.shop.sync.adapter", mapAdapterClassName = "SyncMapConvertMapperAdapter")
public class MapStructPlusConfiguration {

}

项目结构
sync
|
|_common(里面有model包)
|
|_starter(里面有config包和SyncApplication)

**Comment by linpeilie** [comment]
要在同一个模块下才能生效
