### ISSUE TITLE
生成实现类不在启动模块

### ISSUE THREAD

**Issue by wzkris** [linpeilie/mapstruct-plus#44]
mapstruct-plus-spring-boot-starter 版本1.3.5 ；
![image](https://github.com/linpeilie/mapstruct-plus/assets/90759163/1edacff9-6397-444a-8848-947ac280f99d)

该依赖被我放入core包下，微服务模块依赖core包，但是生成的映射在core包下，导致映射报错
![image](https://github.com/linpeilie/mapstruct-plus/assets/90759163/68c8f547-2f3f-4238-9457-3e30d6696b1b)
断点发现converter实现类没有加载到map里

jdk版本17，请排查一下问题

**Comment by linpeilie** [comment]
SpringBoot启动的时候，可以扫描到core包内的类么

**Comment by wzkris** [comment]
> SpringBoot启动的时候，可以扫描到core包内的类么

ok已解决
