### ISSUE TITLE
mvn package 找不到AutoMapperConfig类

### ISSUE THREAD

**Issue by yaoliu108** [linpeilie/mapstruct-plus#45]
<img width="1234" alt="image" src="https://github.com/linpeilie/mapstruct-plus/assets/28888340/b28a9052-7fb2-449c-a482-38d6c04bf908">
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.verison}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.github.therapi</groupId>
                            <artifactId>therapi-runtime-javadoc-scribe</artifactId>
                            <version>${therapi-javadoc.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot.version}</version>
                        </path>
                        <path>
                            <groupId>io.github.linpeilie</groupId>
                            <artifactId>mapstruct-plus-processor</artifactId>
                            <version>${mapstruct-plus.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${mapstruct-plus.lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>`

<img width="618" alt="image" src="https://github.com/linpeilie/mapstruct-plus/assets/28888340/0a2864a5-423b-4265-8351-aa4c35243a4e">

**Comment by linpeilie** [comment]
什么版本

**Comment by yaoliu108** [comment]
> 什么版本

  <mapstruct-plus.version>1.3.5</mapstruct-plus.version>
        <mapstruct-plus.lombok.version>0.2.0</mapstruct-plus.lombok.version>
        <lombok.version>1.18.28</lombok.version>


这是一个父子多个项目组成，有的子项目能打进来，有的子项目就打不进来。
<img width="510" alt="image" src="https://github.com/linpeilie/mapstruct-plus/assets/28888340/edaa6bac-8123-4a16-abb4-11f87feddbe4">

**Comment by linpeilie** [comment]
能提供一个可以复现的项目样例么，或者加下我的联系方式

**Comment by yaoliu108** [comment]
> 能提供一个可以复现的项目样例么，或者加下我的联系方式

怎么加到您的联系方式？

**Comment by linpeilie** [comment]
项目首页
