### ISSUE TITLE
是否支持@SuperBuilder或者@Builder

### ISSUE THREAD

**Issue by hugzero** [linpeilie/mapstruct-plus#51]
不使用@Data注解只有@Getter和@SuperBuilder注解；
MapperImpl支持自动build吗

**Comment by hugzero** [comment]
<compilerArgs>
     <arg>-Amapstruct.plus.builder.disableBuilder=false</arg>
 </compilerArgs>
加上这个配置解决

**Comment by linpeilie** [comment]
也可以用配置类的方式 `MapperConfig`
