### ISSUE TITLE
支持驼峰转下划线和下划线转驼峰吗？

### ISSUE THREAD

**Issue by Skqing** [linpeilie/mapstruct-plus#65]
前端form传参要求下划线，后台属性定义都是驼峰，是否考虑支持驼峰转下划线和下划线转驼峰

**Comment by linpeilie** [comment]
这个可以通过指定JSON序列化的字段来实现

**Comment by Skqing** [comment]
> 这个可以通过指定JSON序列化的字段来实现

是，但我们前端接收的时候是下划线，然后其他也服务使用的驼峰，这里有个转换过程，所以想在这个转换过程里处理，不然要手动JSON序列化再反序列化一次，这样很浪费。

**Comment by linpeilie** [comment]
并不冲突，看你目前的描述是应该有两个类，一个适配前端一个适配其他系统.。适配前端的指定序列化字段名称就好了，在接收数据时自动转换的，不需要再手动处理

**Comment by Skqing** [comment]
> 并不冲突，看你目前的描述是应该有两个类，一个适配前端一个适配其他系统.。适配前端的指定序列化字段名称就好了，在接收数据时自动转换的，不需要再手动处理

问题在于适配前端的DTO是form传参方式，不是JSON传参方式，无法指定名称

**Comment by Skqing** [comment]
当然了，这目前可能只是我个人的需求，如果实现困难或者没有太大必要那我凑合手动转换也是可以的。

**Comment by linpeilie** [comment]
可以先通过 `AutoMapping` 的 `target` 属性来指定实现，这个功能确实非常少见，暂时先不考虑适配
