### ISSUE TITLE
两个模块之间的DTO和DO转换该如何配置呢？

### ISSUE THREAD

**Issue by Skqing** [linpeilie/mapstruct-plus#68]
A模块里面是DO，B模块里面是DTO，B模块依赖A模块，但A模块不可能依赖B模块。需求是两个模块里面的DO和DTO能相互转换，但目前好像没办法实现，因为注解@AutoMappers是加在A模块的DO上的，这样DO传DTO可以，但反过来就不行了，因为B模块没有依赖A模块，A模块下的generated-sources没有生成代码。
![image](https://github.com/linpeilie/mapstruct-plus/assets/1713001/6c2b2ac2-93b3-4b80-ad66-aba9e0ca444f)

**Comment by linpeilie** [comment]
默认情况下，配置了`AutoMapper`/`AutoMappers`，就会生成两个类之间的转换接口，会生成在B模块，A模块中并没有

**Comment by Skqing** [comment]
那就奇怪了，我构建报错Couldn't retrieve @Mapper annotation，但已经没有额外的mapstruct依赖了。
![image](https://github.com/linpeilie/mapstruct-plus/assets/1713001/9e992f05-d5ff-4916-a30f-299d8f4e424f)

**Comment by Skqing** [comment]
另外，能不能在@MapperConfig或者其他地方增加一个配置项入库，让用户可以去掉@AutoMapper，用代码去自定义配置转换映射，有时候有A和B两个模块都不方便依赖@AutoMapper

**Comment by linpeilie** [comment]
肯定有的，mapstructplus内置的版本是1.5.5，你这显示的是1.4.2，可以看看springfox-swagger2这个依赖，这个也依赖了mapstruct

**Comment by linpeilie** [comment]
> 另外，能不能在@MapperConfig或者其他地方增加一个配置项入参，让用户可以去掉@AutoMapper，用代码去自定义配置转换映射，有时候有A和B两个模块都不方便依赖@AutoMapper。这时候想在C模块（C模块依赖A和B）里面去手动配置。

那这样子和直接使用mapstruct定义Mapper接口一样了吧

**Comment by Skqing** [comment]
> mapstructplus内置的版本确实是1.5.5.Final，应该是我们项目里其他依赖冲突了或者没排除干净。

**Comment by Skqing** [comment]
> > 另外，能不能在@MapperConfig或者其他地方增加一个配置项入参，让用户可以去掉@AutoMapper，用代码去自定义配置转换映射，有时候有A和B两个模块都不方便依赖@AutoMapper。这时候想在C模块（C模块依赖A和B）里面去手动配置。
> 
> 那这样子和直接使用mapstruct定义Mapper接口一样了吧
我们项目里现在用的就是mapstruct，但它的问题是写一个List<Entity>转换方法还必须写一个Entity转换方法，并且还要自己写一这个转换方法的接口，很麻烦。

**Comment by Skqing** [comment]
@AutoMapper里面有四个属性，实际上相当于我们自己new AutoMapper的bean然后注入到配置里面就行了。
![image](https://github.com/linpeilie/mapstruct-plus/assets/1713001/751dd60d-b05a-4d74-a8dc-1554ad93fcb6)

**Comment by linpeilie** [comment]
> @AutoMapper里面有四个属性，实际上相当于我们自己new AutoMapper的bean然后注入到配置里面就行了。 ![image](https://private-user-images.githubusercontent.com/1713001/313060130-751dd60d-b05a-4d74-a8dc-1554ad93fcb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzQ1MDksIm5iZiI6MTcxMDQ3NDIwOSwicGF0aCI6Ii8xNzEzMDAxLzMxMzA2MDEzMC03NTFkZDYwZC1iMDVhLTRkNzQtYThkYy0xNTU0YWQ5M2ZjYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMDM0MzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGIyYmVmZjdmMDlmOTYzMDRkZDRiNzM5OWEzNDMwZjk1NTczZTY2NGRmYTM2ZmQzZjY0ZmMwMmFiY2IwNWJkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.18X4JTGTRvxjJ0NstECoW1k4kUevK_PY1tzguius1p0)

效果是的，自动生成转换接口，具体可以看下文档

**Comment by Skqing** [comment]
还有一种方法就是把@AutoMapper这些注解模块单独拆出来，让A和B模块可以单独依赖。然后在C模块里面依赖具体实现，像springboot配置一个basePackage，然后去扫描这个包下面的@AutoMapper这些注解，生成的实现类都放到C模块里，因为C依赖了A和B，当然了这都是我个人想法，这个改动有多大，不过感觉目前plus还是只考虑单模块的情况，多模块的情况实际应用过程中还是有一些限制。

**Comment by linpeilie** [comment]
扫描包的方式，所用的技术不支持这样子处理。
如果在另一个模块里面配置，例如在C中的C类里面指定A和B的转换关系，这样子和直接定义一个转换接口，里面指定A和B的转换，没有啥区别吧

**Comment by Skqing** [comment]
> 扫描包的方式，所用的技术不支持这样子处理。 如果在另一个模块里面配置，例如在C中的C类里面指定A和B的转换关系，这样子和直接定义一个转换接口，里面指定A和B的转换，没有啥区别吧

是没区别，只是要还想使用@AutoMapper这个注解就比较麻烦了。当然了如果不支持的话只能按照目前的方式使用了，就是ABC模块都依赖plus

**Comment by linpeilie** [comment]
A模块可以不依赖

**Comment by Skqing** [comment]
> A模块可以不依赖

是
