### ISSUE TITLE
支持一个字段映射到多个字段吗

### ISSUE THREAD

**Issue by wkfyynh** [linpeilie/mapstruct-plus#74]
我现在有一个参数适配的场景，通过一个类转换到多个类中，目前通过mappings有的类可以做到一对一所有字段映射,但是个别目标类存在多个字段含义相同字段名不同的场景，但是不能穿空，觉得使用setter去重写不太好。尝试了多配置了一个mapping但是就报错，比如下图中，源类的opStation想转成YHZXPojo中的OP_PROGRAM和OP_SITE字段
![image](https://github.com/linpeilie/mapstruct-plus/assets/22886179/0aebbf1e-52a1-4846-8d03-e968253b76f6)
但是配置了第二个就报错了
![image](https://github.com/linpeilie/mapstruct-plus/assets/22886179/c237c3fc-b248-4711-a737-836e975aed22)

请问下支持这种场景吗？支持的话该怎么配置呢？版本1.3.5

**Comment by linpeilie** [comment]
支持，应该在 `OP_PROGRAM` 和 `OP_SITE` 字段上面配置，target 为 `opStation`

**Comment by linpeilie** [comment]
这个是因为默认生成的反向转换（由目标类生成当前类），有两个属性（`OP_PROGRAM`、`OP_SITE`）都映射到了 `opStation`。

有多种方式可以解决：
1. 在 `AutoMapper` 中配置 `reverseConvertGenerate` 为 `false`
2. 在目标类（`YHZXpojo`）中添加 `AutoMapper` 注解，添加该类
3. 通过 `ReverseAutoMapping` 配置反向转换规则

**Comment by wkfyynh** [comment]
第二种方式试了不行，第一种方式试了可以了，谢谢
