### ISSUE TITLE
子模块同名类转换生成问题

### ISSUE THREAD

**Issue by 8OOOOOOOOD** [linpeilie/mapstruct-plus#75]
M1模块依赖于M2模块, 想要生成 M2模块中的A转换为M1模块中的B1 以及 M2模块中的A转换为M2模块中的B2。
config:
```
@MapperConfig(adapterClassName = "M1ConvertMapperAdapter",
        mapperPackage = "com.m1.model.mapper",
        adapterPackage = "io.github.linpeilie.adapter",
        mapAdapterClassName = "M1MapConvertMapperAdapter")
```

```
@MapperConfig(adapterClassName = "M2ConvertMapperAdapter",
        mapperPackage = "com.m2.model.mapper",
        adapterPackage = "io.github.linpeilie.adapter",
        mapAdapterClassName = "M2MapConvertMapperAdapter")
```

报错: ConflictingBeanDefinitionException: Annotation-specified bean name 'AToBMapperImpl' for bean class [com.m2.model.mapper.AToBMapperImpl] conflicts with existing, non-compatible bean definition of same name and class [com.m1.mapper.AToBMapperImpl]

**Comment by linpeilie** [comment]
A与B1和B2进行转换，怎么会报错 `AToBMapperImpl`，B是哪里来了

**Comment by 8OOOOOOOOD** [comment]
> A与B1和B2进行转换，怎么会报错 `AToBMapperImpl`，B是哪里来了

B就是一个名字, B1、B2的名字都是B(所在模块不同)。M1模块依赖M2模块, 只生成了M1模块中的B的AToBMapperImpl。

**Comment by linpeilie** [comment]
贴下所有类的代码

**Comment by 8OOOOOOOOD** [comment]
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/045697b8-7111-4eb1-ae2c-5424cf5fafa9)
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/14d74b00-24a1-4b7b-800b-9ea3c3852d4d)
ProjectResult都是同一个。
使用时报错:
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/23de4e15-8568-4843-9050-72282cf6d512)

```
io.github.linpeilie.ConvertException: cannot find converter from ProjectResult to ProjectResultVO
```
只生成了teaching模块中类的mapper
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/3439fead-39dc-435d-ba93-856609b298f0)


加了config后:
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/8f6a954e-df03-4e82-82ff-d9e307e1d847)

启动报错:
```
Annotation-specified bean name 'projectResultToProjectResultVOMapperImpl' for bean class [com.metalabs.system.model.entity.ProjectResultToProjectResultVOMapperImpl] conflicts with existing, non-compatible bean definition of same name and class [com.metalabs.teaching.model.mapper.ProjectResultToProjectResultVOMapperImpl]
```

**Comment by 8OOOOOOOOD** [comment]
> 贴下所有类的代码

![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/045697b8-7111-4eb1-ae2c-5424cf5fafa9)
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/14d74b00-24a1-4b7b-800b-9ea3c3852d4d)
ProjectResult都是同一个。
使用时报错:
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/23de4e15-8568-4843-9050-72282cf6d512)

```
io.github.linpeilie.ConvertException: cannot find converter from ProjectResult to ProjectResultVO
```
只生成了teaching模块中类的mapper
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/3439fead-39dc-435d-ba93-856609b298f0)


加了config后:
![image](https://github.com/linpeilie/mapstruct-plus/assets/55775562/8f6a954e-df03-4e82-82ff-d9e307e1d847)

启动报错:
```
Annotation-specified bean name 'projectResultToProjectResultVOMapperImpl' for bean class [com.metalabs.system.model.entity.ProjectResultToProjectResultVOMapperImpl] conflicts with existing, non-compatible bean definition of same name and class [com.metalabs.teaching.model.mapper.ProjectResultToProjectResultVOMapperImpl]
```

**Comment by GIT-GAZZ** [comment]
类名一样好像就会有问题？我今天也遇到类似的，两个内部类名称一样，同时与另外一个类型进行映射，就会报错

**Comment by linpeilie** [comment]
这个是因为Spring同类不同包，注入导致的报错。我考虑下，怎么解决
