### ISSUE TITLE
能不能在automapper生成的mapper里添加beforemapping或aftermapping

### ISSUE THREAD

**Issue by pocketchew** [linpeilie/mapstruct-plus#76]
能不能在automapper生成的mapper里添加@beforemapping或@aftermapping?

例如

@Data
@AutoMapper(target = DependsTarget.class)
public class DependsSource {

    private String firstName;
    private String lastName;

}

@Data
public class DependsTarget {

    private String firstName;
    private String lastName;
    private String fullName;

}

想要在DependsSource转换为DependsTarget时 把DependsTarget.fullName的值设为DependsSource.firstName+DependsSource.lastName
*不能在DependsTarget上使用@AutoMapper

或者有什么其他方法能做到类似的结果

**Comment by linpeilie** [comment]
- BeforeMapping和AfterMapping在注解中加不了，可以通过use来引入使用。
- 可以使用AutoMapping中的expression来实现

**Comment by nan-www** [comment]
> * BeforeMapping和AfterMapping在注解中加不了，可以通过use来引入使用。
> * 可以使用AutoMapping中的expression来实现

请问应该如何通过use引入来实现afterMapping的语义呢？
直接通过qualifiedByName来调用afterMapping的方法？

**Comment by linpeilie** [comment]
> > * BeforeMapping和AfterMapping在注解中加不了，可以通过use来引入使用。
> > * 可以使用AutoMapping中的expression来实现
> 
> 请问应该如何通过use引入来实现afterMapping的语义呢？ 直接通过qualifiedByName来调用afterMapping的方法？

https://github.com/linpeilie/mapstruct-plus/blob/main/example/spring-boot-with-lombok/src/main/java/io/github/linpeilie/me/callbacks/ClassContainingCallbacks.java

可以参考这个示例类

**Comment by nan-www** [comment]
> > > * BeforeMapping和AfterMapping在注解中加不了，可以通过use来引入使用。
> > > * 可以使用AutoMapping中的expression来实现
> > 
> > 
> > 请问应该如何通过use引入来实现afterMapping的语义呢？ 直接通过qualifiedByName来调用afterMapping的方法？
> 
> https://github.com/linpeilie/mapstruct-plus/blob/main/example/spring-boot-with-lombok/src/main/java/io/github/linpeilie/me/callbacks/ClassContainingCallbacks.java
> 
> 可以参考这个示例类

我确实是这么使用的。但是被afterMapping修饰的方法并没被调用。
```@Component
@Slf4j
public class MapStrcutPlusConvertor {

    @Autowired
    private BeanUtil beanUtil;

    @Named("arr2Str")
    public String arr2Str(List<String> arr) {
        return JsonTool.toJson(arr);
    }

    @Named("map2Str")
    public String map2Str(Map<String, String> map) {
        return JsonTool.toJson(map);
    }

    @AfterMapping
    public void after(@MappingTarget SonVo sonVo){
        List<String> integers = List.of("1", "2", "3");
        List<String> reverse = beanUtil.reverse(integers);
        log.info("[after] son:{}, reverse: {}", sonVo, reverse);
    }

}

@EqualsAndHashCode(callSuper = true)
@Data
@AutoMapper(target = SonVo.class, uses = MapStrcutPlusConvertor.class, reverseConvertGenerate = false)
public class Son extends Father{
    private String name;
    private int age;
    @AutoMapping(target = "hobbies", qualifiedByName = "arr2Str")
    private List<String> hobbies;
    @AutoMapping(target = "extra", qualifiedByName = "map2Str")
    private Map<String, String> extra;
}
```

**Comment by linpeilie** [comment]
看下生成的转换实现类代码呢，是什么样子的。

**Comment by nan-www** [comment]
> 看下生成的转换实现类代码呢，是什么样子的。

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2025-02-17T20:31:40+0800",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 17.0.14 (Azul Systems, Inc.)"
)
@Component
public class SonToSonVoMapperImpl implements SonToSonVoMapper {

    private MapStrcutPlusConvertor mapStrcutPlusConvertor = SpringContextUtils4Msp.getBean("mapStrcutPlusConvertor", MapStrcutPlusConvertor.class);

    @Override
    public SonVo convert(Son source) {
        if ( source == null ) {
            return null;
        }

        SonVo sonVo = new SonVo();

        sonVo.setHobbies( mapStrcutPlusConvertor.arr2Str( source.getHobbies() ) );
        sonVo.setFatherField( source.getHighField() );
        sonVo.setExtra( mapStrcutPlusConvertor.map2Str( source.getExtra() ) );
        sonVo.setName( source.getName() );
        sonVo.setAge( source.getAge() );

        return sonVo;
    }

    @Override
    public SonVo convert(Son source, SonVo target) {
        if ( source == null ) {
            return target;
        }

        target.setHobbies( mapStrcutPlusConvertor.arr2Str( source.getHobbies() ) );
        target.setFatherField( source.getHighField() );
        target.setExtra( mapStrcutPlusConvertor.map2Str( source.getExtra() ) );
        target.setName( source.getName() );
        target.setAge( source.getAge() );

        return target;
    }
}
```

**Comment by linpeilie** [comment]
看生成的代码没有问题，在用到 `mapStrcutPlusConvertor.arr2Str` 这个方法的地方打个断点看一下呢。

**Comment by nan-www** [comment]
> 看生成的代码没有问题，在用到 `mapStrcutPlusConvertor.arr2Str` 这个方法的地方打个断点看一下呢。

这里打断点应该看不出什么吧？
生成的代码中并没有看到`after` 方法的调用。
