### ISSUE TITLE
泛型上界问题

### ISSUE THREAD

**Issue by wzkris** [linpeilie/mapstruct-plus#78]
![image](https://github.com/linpeilie/mapstruct-plus/assets/90759163/c11b8c45-bf02-4f6f-aa42-c1404ff4c24f)
![1712990300295](https://github.com/linpeilie/mapstruct-plus/assets/90759163/a5a93aa4-88a0-4b4a-93b2-f5103e418cd4)
但是生成的代码报错，如下
![image](https://github.com/linpeilie/mapstruct-plus/assets/90759163/e57cf96e-0d44-442f-8d75-e870d5b037c3)
但是我用set编译器就不会报错

**Comment by linpeilie** [comment]
这个是mapstruct处理集合默认策略的问题。


MapStruct 提供的解决方案是在 `Mapper` 注解中，配置  `collectionMappingStrategy = CollectionMappingStrategy.TARGET_IMMUTABLE`。
但 MapStructPlus 的 `AutoMapper` 注解暂时没有增加该配置项。

可以通过如下方式临时解决：

自定义两个转换接口：
- `LoginUserToLoginUserVOMapper` 继承自 `BaseMapper<LoginUser, LoginUserVO>`，增加 `Mapper` 注解，及配置项：`collectionMappingStrategy `
- 同理增加 `LoingUserVOToLoginUserMapper`

这样子可以临时解决该问题，下个版本增加 `collectionMappingStrategy` 配置项

**Comment by linpeilie** [comment]
增加自定义转换接口后，`LoginUser` 和 `LoginUserVO` 的 `AutoMapper` 注解需要去掉
