### ISSUE TITLE
v1.4.0 AutoMappings 生成同名

### ISSUE THREAD

**Issue by deng-cc** [linpeilie/mapstruct-plus#80]
配置实体类如下
![PixPin_2024-04-29_14-00-43](https://github.com/linpeilie/mapstruct-plus/assets/18366406/6cbac220-e4b8-4c4d-aca9-f035b3eb496f)
![PixPin_2024-04-29_14-01-02](https://github.com/linpeilie/mapstruct-plus/assets/18366406/d1c4606e-5c40-4da4-a03a-c9956cfd33d7)

然后在1.3.5的表现正常，1.4.0时出现了错误，帮帮孩子😭
- 1.3.5
![PixPin_2024-04-29_13-46-11](https://github.com/linpeilie/mapstruct-plus/assets/18366406/ff95790b-abb6-4771-a556-03e788a83793)

- 1.4.0
![PixPin_2024-04-29_14-00-20](https://github.com/linpeilie/mapstruct-plus/assets/18366406/40234131-5300-421a-bd2d-3effb2cd71e4)

**Comment by linpeilie** [comment]
`RaceEventExportVO` 和 `FlatRaceEventExportVO` 是父子类，1.4.0 后兼容了可以只配置父类，所有子类都生效的逻辑。但没有兼容同时配置的场景，下个版本修复下
