### ISSUE TITLE
有没有计划支持MapStruct Spring Extensions,以及生成的接口继承公共接口功能

### ISSUE THREAD

**Issue by jakaz1280** [linpeilie/mapstruct-plus#88]
MapStruct Spring Extensions让MapStruct使用 Spring 的Converter接口,并且会放入ConversionService中,使用ConversionService进行转换,因为有的老项目里是这么使用的,大神能加入MapStruct Spring Extensions的支持的话,改动可能少一些,感激大神.

还有因为MapStruct的接口中如果存在符合类型的方法会自动使用,比如接口里一个方法入参是Collection返回值类型是 String,
在转换的时候,原类和目标类里同名的的Collection和String会自动应用这个方法,如果有接口继承功能,可以把这种方法写到需要继承的接口里,自己手动写MapStruct的转换接口的时候可以继承这个接口,如果MapStruct Plus自动生成的也能继承就更好了,感谢大神.

**Comment by linpeilie** [comment]
适配不了。

1. MapStruct Spring Extensions 强依赖 Spring
2. 这两个项目的部分设计类似，但 MapStruct Spring Extensions 所支持的功能（特性）要少很多，强行适配，MapStruct Spring Extensions 没法全部支持 MapStructPlus，如果使用 MapStructPlus 的方式来调用转换逻辑，可能会有多种特性不支持等各种未知的问题。反之，和只使用 MapStruct Spring Extensions 没有什么两样。
