### ISSUE TITLE
大量使用AutoMapper进行转换时，构建效率低

### ISSUE THREAD

**Issue by Trailer98** [linpeilie/mapstruct-plus#89]
<img width="974" alt="image" src="https://github.com/linpeilie/mapstruct-plus/assets/57579753/f4789e19-2203-4f0d-88b5-1228136f602d">
因为使用的地方比较多，ConvertMapperAdapter已经到了接近15000行，每次改某一个带有@AutoMapper的实体类时，一构建就要花10分钟左右来重新生成文件

**Comment by linpeilie** [comment]
😢我考虑下能不能优化下，有点难搞

**Comment by linpeilie** [comment]
方便的话，可以加下我的联系方式，改后能在你的项目中帮忙测试一下

**Comment by Trailer98** [comment]
发你邮箱了
