### ISSUE TITLE
这种Page的复杂类型怎么转换

### ISSUE THREAD

**Issue by yongoe1024** [linpeilie/mapstruct-plus#91]
Page<SysConfig> page = sysConfigService.selectByPage();
  Page<SysConfigVo> vo = converter.convert(page, SysConfigVo.class);

Page的类型如下
public class Page<T>{
    protected List<T> records;
    protected long total;
    protected long size;
}

**Comment by linpeilie** [comment]
Page 声明构造对象，传入这三个参数，其中 list 调用转换逻辑转换成需要的对象即可
