### ISSUE TITLE
 大佬帮看看cannot find converter from RegisterDto to SysUser

### ISSUE THREAD

**Issue by yongoe1024** [linpeilie/mapstruct-plus#92]
<img width="1128" alt="7201440d8481a8c13de00b4a5cad4a1e" src="https://github.com/linpeilie/mapstruct-plus/assets/84385942/effe93d0-aaef-4137-842f-9c16e7b37aec">
<img width="830" alt="4dfc778ff5ec13c41a7dff6512412f79" src="https://github.com/linpeilie/mapstruct-plus/assets/84385942/550db810-d5cf-49de-92c8-a721ff15c864">

**Comment by linpeilie** [comment]
看下常见问题
