### ISSUE TITLE
多模块,与 lombok 整合,未生成

### ISSUE THREAD

**Issue by LuChangQiu** [linpeilie/mapstruct-plus#94]
**项目结构 :**
![image](https://github.com/user-attachments/assets/ad350431-3328-4128-9e54-44c555d29460)

**pom文件配置: **
配置在了start层的pom文件下,lombok版本:1.18.34 mapstruct-plus版本:1.4.3
![image](https://github.com/user-attachments/assets/0e90c3e4-088c-4a77-8641-f199ce9e61f9)

应用在dto层
![image](https://github.com/user-attachments/assets/b29d8c2f-326b-477a-bc05-11f7ab979c8b)

**Comment by linpeilie** [comment]
`maven-compiler-plugin` 配置在start，dto模块并不会生效

**Comment by LuChangQiu** [comment]
好滴好滴 解决啦 感谢作者大大
