### ISSUE TITLE
跨模块使用枚举映射会有问题

### ISSUE THREAD

**Issue by Inseparable-Bird** [linpeilie/mapstruct-plus#95]
![image](https://github.com/user-attachments/assets/c4eff438-4f61-4be8-b040-5d5902f0c8ac)
![image](https://github.com/user-attachments/assets/3c710465-7d98-4f46-aab2-3eb4ce6df7b4)
![image](https://github.com/user-attachments/assets/20bcdea7-6246-4e16-a9d3-559612065576)
![image](https://github.com/user-attachments/assets/0627f6b7-3df5-422b-adbc-da9210f21fbc)
跨模块使用枚举映射会有问题

**Comment by linpeilie** [comment]
UserTypeMapper看下有生成么
