### ISSUE TITLE
请教一个使用场景的问题

### ISSUE THREAD

**Issue by wkfyynh** [linpeilie/mapstruct-plus#97]
我们现在有很多实体类都是驼峰格式，我们调用三方接口的时候大都是下划线格式，我们目前每个字段都通过@Automapping 指定target来进行适配驼峰转下划线。这种配置起来很繁杂，并且重复度很高，请问下有没有类似全局自定义转换器，每个类上引用一下，这样字段上就不用每个都加@Automapping 进行映射了。

**Comment by linpeilie** [comment]
不支持这种场景。
但在调用第三方接口，序列化结果的时候，JSON序列化工具可以做这些事情。

**Comment by wkfyynh** [comment]
好的
